#markdown: rdiscount
#pygments: true
#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - with_toc_data
    - tables
highlighter: pygments
plugins: ./_plugins
paginate: 8
safe: false

#站点基础配置
title: 雨落空林 
subTitle: Be Happy.
description: 记录生活的点滴
url: http://joyocaowei.github.io
#url: http://localhost:4000
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我 
    url: /contact.html

#归档类型
archives:
  - id: sort_by_pubdate
    text: 按日期归档
  - id: sort_by_categories
    text: 按类别归档

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
#  - class: fa-google-plus
#    url: http://www.zhanxin.info
#  - class: fa-facebook
#    url: http://www.zhanxin.info
  - class: fa-github
    url: http://github.com/joyocaowei
  - class: fa-weibo
    url: http://weibo.com/1710716145
#  - class: fa-renren
#    url: http://www.zhanxin.info
#  - class: fa-pinterest
#    url: http://www.zhanxin.info
#  - class: fa-twitter
#    url: http://www.zhanxin.info
  - class: fa-rss
    url: http://joyocaowei.github.io

#作者信息
author:
  name: joyocaowei
  email: joyocaowei@gmail.com
  link: http://joyocaowei.github.io/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
duoshuo:
  config: true
  id: joyocaowei 

disqus:
  config: false
  id: 
